services:

  redis:
    image: redis
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: invo-service:latest
    ports: 
      - "8080:8080"
    volumes:
      - ./data:/data:rw
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      