services:

  redis:
    image: redis
    ports:
      - "6379:6379"

  invo-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: invo-service:latest
    ports: 
      - "8080:8080"
    volumes:
      - ./data:/data:rw
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      INVO_API_HOST: "localhost"
      INVO_API_PORT: "8080"
      ENV: "development"
  
  frontend:
    build:
      context: ../invo-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:5173"
    volumes:
      - ../invo-frontend:/app:rw
      - /app/node_modules
    depends_on:
      - invo-service
    environment:
      VITE_API_URL: http://localhost:8080
      NODE_ENV: production